### ISSUE TITLE
zusätzliche grüne Pfeile an fast allen Linien

### ISSUE THREAD

**Issue by Iwan1803** [Axel32019/FS19_AutoDriveLive#1]
Ich habe nun die aktuellste AD-Version anhand deiner Anleitung manipuliert und an fast allen Verbindungspunkten erscheinen nun zusätzliche grüne **>**, sowohl an grünen als auch blauen Linien.
Ist das gewollt oder ein Bug?
![fsScreen_2019_11_15_20_55_41](https://user-images.githubusercontent.com/47528836/68971757-8d256000-07ea-11ea-96b4-132ec814e196.jpg)

**Comment by Axel32019** [comment]
Das ist nicht gewollt und m.E. hab ich da auch nichts implementiert. Hab't ihr einen Anhaltspunkt wo ich diese "Pfeile" suchen könnte?

**Comment by Iwan1803** [comment]
Gute Frage, keine Ahnung.
Vorhin habe ich noch mit der AD-Version von gestern abend gespielt und da war es noch nicht so.
Dann habe ich die aktuellste Version runtergeladen, deinen Mod eingebaut und nun habe ich diese Pfeile. Möglicherweise ist es also ein "Bug" von der AD-Version selber.

**Comment by Axel32019** [comment]
Hab die Version 1.0.6.8 Release als Basis und da sind die auch drin.

**Comment by Iwan1803** [comment]
Ich wollte gerade an der Raffinerie die Einfahrt aus Richtung Hafen kommend korrigieren, weil die Kurve da viel zu eng ist, aber ich kann einige der komischen Pfeile erst gar nicht mehr löschen. Es sieht so aus als ob da mehrere Wegpunkte übereinander liegen.
Das werde ich wohl mal bei Stephan als Issue posten.

**Comment by Iwan1803** [comment]
Ich habe nun das Backup vor der letzten Neuberechnung wiederhergestellt und sobald neu berechnet wird, erscheinen diese seltsamen Pfeile wieder.
Ein Löschen von der modifizierten AD-Version und neu runterladen der selbsterstellten ZIP hat scheinbar erstmal wieder alles "korrigiert".
Es scheint also etwas mit deiner Modifikation zu tun zu haben.

**Comment by Iwan1803** [comment]
Ich habe nun deinen Mod wieder eingebaut und schon tauchen auch die Probleme wieder auf und zwar ab dem Zeitpunkt, wo ich das erste Fahrzeug per AD auf eine Tour schicke.
Folgende Änderungen an den Dateien habe ich vorgenommen (gem. Anleitung):
![AD-Mod](https://user-images.githubusercontent.com/47528836/68981537-09786d00-0804-11ea-9606-7410244b5a75.jpg)
Irgendwas passt da nicht so ganz...

**Comment by Axel32019** [comment]
Das ist soweit alles genau wie vorgesehen - die Funktion AutoDrive:FastShortestPath habe ich nach AutoDriveDijkstraLive.lua verlagert. Ich schaue mir das aber trotzdem mal an...

**Comment by haamic** [comment]
Hallo,
das mit den Pfeilen kann ich bestätigen.  An allen vorhanden Wegpunkten, egal ob grün oder blau erscheinen grüne Pfeilspitzen. Diese zeigen von Ost nach west und sind nicht löschbar.
Bei neu eingefahrenen Strecken zu einem neuen Ziel, erscheinen diese erst nach dem die Fahrt dahin gestartet wurde.
Die Funktionalität des Live-Modus hab ich getestet. soweit scheint er zu funktionieren. Ein zusätzliches Ziel auf vorhandenem Streckennetz, sowie ein zusätzliches Ziel mit neu eingefahrener Strecke dahin, konnte ohne Neuberechnung angefahren werden.
Allerdings hab ich das Problem, das im Modus Abholen abliefern das Fahrzeug beim Ablieferziel nicht ankommt. es führt nur ein Weg dahin. Das Fahrzeug fährt aber nicht auf diesem weg, sondern auf der benachbarten Strecke Richtung Ziel, kommt da nie an und startet dann wieder zum Abholen.
Möglicherweise eher ein AD Problem als vom Live-Modus?
Schönes Wochenende
Gruss Micha

**Comment by Axel32019** [comment]
@Iwan1803 @haamic Neue Version verfügbar: Pfeile sind weg, Editieren der Wegpunkte funktioniert auch.
@haamic Dein letztgenanntes Promblem sehe ich bei AD.

**Comment by Woife1** [comment]
Gab es nicht schon einmal ein Problem mit komischen Zeichen bei AD?

@haamic welche AD Version hast du umgebaut?

**Comment by haamic** [comment]
@Woife1 
Hatte ich heute morgen aktuell geladen. 1.0.6.8-10 stand im HUD. 
werd es nochmal ohne "Live-Umbau" testen

**Comment by Woife1** [comment]
Das wollt ich auch bald machen ;)  
einfach mal gegen checken

**Comment by Woife1** [comment]
Gerade mit der AD Version von heute Mittag getestet (.6.8-10) Abholen und Anliefern funktioniert
Mal schauen wie es mit der umgebauten Version ist -> Hat funktioniert 
Beide male Scania mit Benalu Optiliner  auf der NF 4fach ohne Wiederholungen

Eins ist mir aufgefallen wenn man einen Drescher Abfahrer am Zielpunkt (Feld) startet bleibt er nicht aktiv

**Comment by Woife1** [comment]
@Axel32019 
ist in der aktuellen Version schon die Implementierung von neuen Wegpunkten/Zielen ohne Neuberechnung drinnen?

Noch ne andere Idee wie wärs mit nem Discord Server zum treffen beim testen und einfacheres absprechen für Fehlerfindung und so

**Comment by Axel32019** [comment]
@Woife1 "die Implementierung von neuen Wegpunkten/Zielen ohne Neuberechnung drinnen?" - Schon von der ersten Version an. Das ist doch der Hauptgrund für das Ganze!!!
Mit Discord kenn ich mich noch garnicht aus. Schick / poste bitte mal einen Link, dann kann ich mich ja mal damit beschäftigen...

**Comment by Woife1** [comment]
👍  Mir kam gerade die Frage in den Kopf und hab nicht gleich eine Antwort gefunden

https://discordapp.com/download  ist wie Teamspeak nur das es für User inkl eigenem Server kostenlos ist ;)

Bisher kann ich nur sagen funktioniert 👍  ❤️

**Comment by Iwan1803** [comment]
Geht auch im Browser, aber ist dann nicht ganz so komfortabel 😉

**Comment by Woife1** [comment]
Ich hab mir mal nen Discord Server erstellt ;) https://discord.gg/mxmkmj

Zum eigentlichen Thema die komischen extra Pfeile kann ich nicht finden (hab auch erst mit der heutigen Version das Testen angefangen)

**Comment by Axel32019** [comment]
Die extra Pfeile sind seit heute gefixt: https://github.com/Axel32019/FS19_AutoDriveLive/issues/1#issuecomment-554623326

**Comment by Iwan1803** [comment]
Es gibt übrigens eine AD-Discord-Gruppe:
https://discord.gg/F3kvkb

**Comment by Woife1** [comment]
Ich hab ein Manko gefunden ;)
Ohne Neuberechnung verschieben sich die gesetzten Zielpunkte wenn man neue hinzufügt bzw. die Fahrer kommen mit den gestzten Zielen nicht mehr ganz klar (wirkt ähnlich wie "mehrere Ziele nutzen" auf ja)
liegt eher an AD selber    habs dort auch mal als request eingestellt

**Comment by Iwan1803** [comment]
Wäre aber ja ein eigenes neues Issue, da es nichts mehr mit den grünen Pfeilen zu tun.
Daher schließe ich mein Issue hier mal, da es ja gelöst worden ist.
