### ISSUE TITLE
Feedback, die 2.

### ISSUE THREAD

**Issue by Iwan1803** [Axel32019/FS19_AutoDriveLive#3]
Gestern abend und gerade konnte ich eine neue Produktion anbinden und alles hat problemlos funktioniert. Erst habe ich die Wege aufgezeichnet, anschließend 3 neue Zielpunkte gesetzt und alle waren direkt danach auch problemlos anfahrbar.

Ein Manko hatte ich allerdings, denn ich habe auch etliche Wegpunkte gelöscht, die von einem meiner Abfahrer hätten genutzt werden sollen. Dieser wollte sich eigentlich auf den Weg zum Silo machen und kam dort zwar auch an, aber lud einfach nicht mehr ab. Ich musste das Spiel speichern, neu laden und dann klappte auch wieder die automatische Tour inkl. Abladen.

Bisher also eigentlich alles soweit problemlos. Hat Stephan sich eigentlich schon mal geäußert?

**Comment by Woife1** [comment]
Stephan hat sich noch nicht geäußert (zumindest mir nicht bekann)
er will es aber auch noch selber mal testen ;)

**Comment by Axel32019** [comment]
Dank an alle die mittesten!

@Iwan1803 Als Ziel lese ich den bei Aufruf der Routenberechnung den aktuellen markerName (AutoDrive.mapMarker[i].name) und verwende den zugehörigen Wegpunkt als Ziel. Wenn sich also der Zielpunkt ändert während ein Abfahrer es nicht "grün" hat, sollte er m.E. trotzdem am Ziel auch ankommen. Warum er nicht abgeladen hat kann ich nicht beantworten.

Aktuell teste ich noch die 4. Optimierung - ist jedoch etwas kritischer. In englisch würde ich die Bezeichnung "uninitialized tables" verwenden, zu deutsch: Eine nicht mit Daten versehene Tabelle. Das verkürzt die Routen-Berechnungs-Zeit bei mir gefühlt nochmal ein ganzes Stück, jedoch wie schonmal erwähnt nicht wirklich messbar.

**Comment by Woife1** [comment]
Das mit dem abladen kann evtl daher kommen das die Trigger nicht richtig erkannt werden?
es gibt ja auch das Problem mit den Planen auf Anhängern die beim Trigger nicht aufgehen

**Comment by Iwan1803** [comment]
Der Zielpunkt des Abfahrers wurde nicht verändert, sondern nur die Strecke dahin. Warum er zwar angekommen ist, aber dann nicht abgeladen hat, kann ich nicht sagen.

Wenn es nur mess- aber keine fühlbaren Vorteile bringt, warum dann eine 4. Optimierung? Die jetzige ist gefühlt doch schon ein Quantensprung 😎

**Comment by Woife1** [comment]
Wenn ich das Prinzip richtigt verstanden hab hat der Fahrer eine Kopie der Wegpunkte nach der Berechnung für sich selbst

**Comment by Axel32019** [comment]
Im Init werden ca. 40000 Werte in 3 Tabellen initialisiert von denen während der Berechnung nur ca. 2000 benötigt werden halte ich eben für (Rechen-) Zeitverschwendung. Und solange ich die Idee noch im Kopf habe probiere ich's halt mal...

**Comment by Axel32019** [comment]
@Iwan1803 Ist hier noch etwas offen? Wir verfolgen den aktuellen Stand ja in dem anderen Issue.

**Comment by Iwan1803** [comment]
Nein, es war ja auch "nur" ein Feedback.
