### ISSUE TITLE
Strecke nicht mehr befahrbar, ohne Live funktioniert es

### ISSUE THREAD

**Issue by haamic** [Axel32019/FS19_AutoDriveLive#4]
@Axel32019 
Heute stellte ich fest, das eine Strecke nicht mehr befahren wurde. Das Fahrzeug nahm immer einen anderen viel längeren Weg. Bin dann direkt auf die Strecke und hab versucht zu Starten,eine Meldung das Kein Weg zum Ziel gefunden werden konnte erschien nicht, wie sonst üblich. Aber das kann ja an AD liegen,das da was geändert wurde. AD wurde sofort wieder inaktiv. Ich hatte das Fahrzeug Punkt für Punkt vorwärts bewegt und jedesmal versucht AD zu Starten. Ab irgendeinem Punkt gings dann mal wieder, aber die Gründe dafür sind mir unerklärlich. hab die vorherige Streckenpunkte gelöscht und neu angelegt, kein Erfolg. 
Da scheint noch irgendwas nicht mit dem Livemodus zu stimmen. 
An anderer Stelle ist mir auch aufgefallen, das LIVE anders fuhr als das herkömmliche AD, aber da hatte es zumindest nicht solche Auswirkungen, das der Weg sooo lang wurde bzw. das eine Strecke nicht mehr befahrbar war.
 
Ich nutzte dann die Aktuelle 1.0.6.9.-13 ohne live modus und die Strecke konnte anstandslos wieder befahren werden.

Gruss Micha

**Comment by Woife1** [comment]
Auf welcher Karte bist du unterwegs? 
und wo gehen die Strecken nicht?

**Comment by haamic** [comment]
An irgendeiner Kreuzung weigert sich LIVE den richtigen Weg einzuschlagen, weil es wahrscheinlich keinen Weg zum Ziel findet. Wie gesagt ohne LIVE gehts wunderbar.
Karte und Welche Strecken ist dabei uninteressant, **ist nicht bös gemeint, versteh das  bitte nicht falsch**.
AD ohne LIVE arbeitet normal, LIVE streikt und fährt unnötige Umwege. das wollte ich nur kundtun.

**Comment by Woife1** [comment]
ich wollt nur versuchen es nachzustellen und bei der Fehlersuche helfen warum es die Punkte nicht benutzt

**Comment by Axel32019** [comment]
Hallo Micha,
Danke für die Rückmeldung.
Eine direkte Meldung das kein Weg gefunden wird gibt es derzeit nicht, jedoch den log-Eintrag "[AutoDrive] Encountered a problem during initialization - shutting down".
Du kannst zusätzlich in der Datei "AutoDriveDijkstraLive.lua" in Zeile 297 "--	print(string.format("axel: AutoDrive:dijkstraLiveShortestPath ERROR ..." die Kommentar-Zeichen "--" am Zeilenanfang entfernen, dann wird im log und Console sichtbar das keine Route gefunden wurde.
Eine nicht befahrbare Route tritt auf wenn darauf Verbindungen mit einem Winkel >90 Grad auftreten.
Das ist sicherlich auch der Grund für das Problem an "irgendeiner Kreuzung" -> Winkel >90 Grad => nicht befahrbar. So ist das in AD gewünscht.

Das etwas andere Fahren liegt sicherlich daran das die Einstellung "Schnellste/kürzeste" Route aus mir nicht erklärlichen Gründen nicht im Algorithmus "ankommt".
Ich habe daher als Default die Einstellung "Schnellste" eingestellt. Dies kann durchaus zu längeren (aber schnelleren) Routen führen.

Es würde helfen wenn Du die Zeile 297 anpasst und wenn die Fehler auftreten im log nach "dijkstraLiveShortestPath ERROR" suchst.
Ein genauere Analyse ist nur mit dem Streckennetz und den Startkoordinaten aus dem Kartenfenster möglich.
Würde mich freuen wenn Du mich/uns hierbei unterstützen würdest.

Gruß
Axel

**Comment by haamic** [comment]
@Axel32019 
Danke für die ausführliche Antwort. 
Mir leuchtet nur nicht ein, das AD damit kein Problem hat. Live beispielsweise biegt links ab und fährt 10 min, AD biegt aber rechts ab und ist in nur 1min am Ziel. Auch gab es mit normalem AD kein Problem mit nicht findbaren Wegen.  An besagter Kreuzung führt der beste Weg rechts über noch eine Kreuzung und dann fast nur geradeaus. ab irgendeinem Wegpunkt der Geraden Strecke hat Live dann wieder zum Ziel gefunden. Vorher nicht. Es gibt keinen Grund, wieso auf einer geraden Strecke kein Weg gefunden werden kann. Wie geschrieben, ohne Live ist das kein Problem. 
Ich habe die Karte an meine Bedürfnisse angepasst, einiges an Veränderungen gemacht. Ich verstehe, das ihr gerne das Problem nachstellen wollt. Damit ihr das  könnt, müsste ich die ganze Karte erst irgendwo hochladen. Dazu hab ich im Moment keine Zeit. Tut mir leid.

**Comment by Axel32019** [comment]
@haamic 
Mir reicht die Datei Autodrive....xml aus dem Savegame und die Startkoordinaten die im Kartenfenster angezeigt werden wenn Du starten möchtest sowie der Name des Ziels. Die Karte hilft mir nicht.
Wenn Du die 1 Min noch findest, bitte die Autodrive....xml als zip hier hochladen, Github akzeptiert nicht alle Datei-Formate

**Comment by haamic** [comment]
Ok wenn das reicht und hilft...
Koordinaten **2394 , 1676**
Ziel : **Abladen Mist-DF** (Ordner Düngerproduktion)
siehe Bild, Rot Korrekter Weg von AD, Gelb Wege von LIVE
![LIVE](https://user-images.githubusercontent.com/28841989/69460804-4e0c8700-0d75-11ea-8225-336921823415.jpg)


[AutoDrive_FS19_Tervalehti_Multifruits_config.zip](https://github.com/Axel32019/FS19_AutoDriveLive/files/3881460/AutoDrive_FS19_Tervalehti_Multifruits_config.zip)

**Comment by Axel32019** [comment]
Hallo Micha und alle die das testen wollen,
Anbei die "Vorab"-Version. Wenn OK mach ich's auf der Startseite "offiziell".

[AutoDriveDijkstraLive.zip](https://github.com/Axel32019/FS19_AutoDriveLive/files/3883976/AutoDriveDijkstraLive.zip)

**Comment by Iwan1803** [comment]
"schnellste" Route geht nach max. Geschwindigkeit, wobei ich nicht weiß, wie er die ermittelt. Geht er nach irgendwelchen Tempolimits von der Karte oder wie berechnet er die?
Daher habe ich bei mir "kürzeste" eingestellt, weil mir auch schon aufgefallen ist, das "schnellste" von der Fahrzeit her nicht unbedingt auch schneller am Ziel ankommen heißt.

**Comment by Axel32019** [comment]
Hallo @Iwan1803,

Ich versuch's mal zu erklären so wie ich es verstehe:
Die Einstellung "schnellste" berücksichtigt den Winkel zwischen den einzelnen Wegpunkten und die eingestellte Maximalgeschwindigkeit des Fahrzeuges wenn kleiner als die definierten Geschwindigkeiten, siehe:

https://github.com/Stephan-S/FS19_AutoDrive/blob/master/FS19_AutoDrive/scripts/AutoDriveGraphHandling.lua

AutoDrive:getDriveTimeBetweenNodes
if angle < 3 then
drivingSpeed = math.min(drivingSpeed, 50)
usw.

Die Einstellung "kürzeste" berücksichtigt nur die Entfernung, keine Geschwindigkeit(en) - was so Sinn macht, siehe:
AutoDrive:getDistanceBetweenNodes

Ob sich zwischen den beiden Einstellungen ein fühl-/messbarer Unterschied ergibt kann ich schwer beantworten.
Das käme auf Vergleichsfahrten mit Stoppuhr an.

Frage: Funktioniert bei Dir prinzipiell soweit alles wie gewünscht?

Gruß Axel

**Comment by Iwan1803** [comment]
Die bisherige Version hat soweit problemlos funktioniert, bis auf die Geschichte mit den 90° am Abfahrer-Punkt am Feld.
Die ZIP von oben bin ich gerade am testen und hatte ein seltsames Phänomen, was ich so bisher noch nicht hatte. Meine beiden Stroh-Sammler (per CP) haben nach dem Abladen am Heizkraftwerk (NFM 4-fach) AD beendet und CP wollte/sollte wieder übernehmen. Beide landeten im Zaun.
Da ich da nicht so drauf geachtet habe, kann ich noch nicht sagen, warum das passiert ist. Das einzige, was ich gesehen habe: die Anzahl Wiederholungen stand auf 3x, was ich bei einer vorherigen Aktion eingestellt hatte. Es könnte gut sein, das beide zum 3. mal am Heizkraftwerk angekommen sind, aber bisher hatte das eigentlich keine Auswirkung. Ich habe es jetzt erstmal wieder auf unendlich gestellt und werde es weiter beobachten.

**Comment by Woife1** [comment]
bei mir ist bzw war es der Heusammler durch das Silo zum Feld wollte 
hab gleichzeitig auch AD aktualisiert

**Comment by Iwan1803** [comment]
Ich habe vorhin CP als auch AD aktualisiert und dann deine neue ZIP reinkopiert (inkl. der Anpassungen in den 2 Dateien). Da wurde ja so einiges in AD verändert.
Gerade ist es übrigens wieder passiert. Nach dem Abladen wurde AD beendet und CP steuert das Gespann dann wieder in den Zaun.

**Comment by Woife1** [comment]
Aktuell ist bei CP ein Issue offen mit Verlinkung auf Stephan 
da hat wohl wer anders was verbockt ;)
https://github.com/Courseplay/courseplay/issues/4605

**Comment by Axel32019** [comment]
Würdet ihr bitte mal in der log-Datei nachsehen ob ihr "dijkstraLiveShortestPath ERROR" darin findet - das ist der Fehlereintrag einer ungültigen ADLive Route. Das ist das einzige was mir gerade einfällt was dann im Zusammenspiel mit CP schief laufen könnte...

**Comment by haamic** [comment]
@Axel32019 Ich konnte nicht eher testen. Scheint aber jetzt so zu funktionieren. Im Livemodus nimmt das Fahrzeug die Route, die sonst auch AD genommen hat. Prima, woran lags denn?
Ich teste und beobachte weiter. Bisher ist mir nichts aufgefallen. In Susammenhang mit CP ist noch nichts testbar gewesen. Danke für deine Arbeit.
Gruss Micha

**Comment by Axel32019** [comment]
@haamic Die Berechnung ist halt "bis aufs Blut" optimiert. Lag noch an einem Fall der "uninitialised tables" - wie ich es nenne...
 Ich kann auch nicht alle eventuell möglichen Karten mit den auftretenden Routen testen ob die richtig herum fahren. Nur durch Eure Rückmeldungen komme ich dann den Problemen auf den Grund.
Danke fürs testen und weiter so.
Gruß Axel

**Comment by Woife1** [comment]
hab gerade nen einzel Test für das Abholen & Anliefern Problem aus CP heraus

kein Error im Log von AD, CP oder der Live Version 
da ist irgendetwas mit den Triggern faul 🤔

**Comment by Woife1** [comment]
Das einzigste das AD nicht mag ist wenn man Ziele löscht die in der config recht weit oben stehen (alles inGame)

**Comment by haamic** [comment]
Also, bei mir gibts auch das Problem. Neuestes AD+CP und dein Test-zip.
Habe gedüngt, Fahrzeug wurde leer, fuhr Dünger aufladen, AD wurde beendet und an CP übergeben, ohne mittels AD zurück zum Feld zu fahren.
keine Fehler im log. Wie oben beschrieben, mit Sicherheit wieder ein neuer AD Fehler.

**Comment by haamic** [comment]
@Axel32019 hab doch was im log gefunden
**Axel: AutoDrive:dijkstraLiveShortestPath ERROR invalid Route count = 2 -> keep Vehicle at start point**
Ist das der Grund, das das Fahrzeug am Start (also beim Dünger laden) bleibt und da schon an CP zurück übergibt?

**Comment by Woife1** [comment]
ich denke der Error kommt wenn ADLive keine Route berechnen kann

**Comment by Axel32019** [comment]
@haamic Würdest Du bitte einen Screenshot vom Fahrzeug + eingeschaltetem AD Kurs hier posten - mal anschauen...

**Comment by Axel32019** [comment]
@Woife1 Genau.

**Comment by haamic** [comment]
Error kam als es zum Auffüllen wollte, aber das Fahrzeug fuhr trotzdem zum Dünger befüllen, muss also eine Route gefunden haben.
Screenshot kommt noch....werd es nochmal nachstellen

**Comment by haamic** [comment]
![Farming Simulator 19 25 11 2019 21_41_36](https://user-images.githubusercontent.com/28841989/69576721-32032280-0fcd-11ea-8bbb-7a3be0250567.jpg)

**Comment by Axel32019** [comment]
@haamic Wenn die beiden Ziele "F53" und "Laden Dünger" noch so sind wie in der config die Du mir geschickt hast, sollten Kurse in beiden Richtungen gefunden werden. In meiner Simu kein Problem.

**Comment by haamic** [comment]
wie ich schon schrieb, es war ja auch kein problem, das Fahrzeug fuhr dahin wo es hin sollte. trotzdem tauchte die Meldung 
**Axel: AutoDrive:dijkstraLiveShortestPath ERROR invalid Route count = 2 -> keep Vehicle at start point**
im log auf.

**Comment by Axel32019** [comment]
Ich werde mal schauen ob ich diese Meldung noch dem Verursacher-Fahrzeug irgendwie zuordnen kann. Momentan kann die von jedem Fahrzeug ins log geschrieben werden.

**Comment by Iwan1803** [comment]
Mein Log ist fehlerfrei und dennoch beendet sich AD ab und zum beim Entladen von Stroh am Heizkraftwerk. Bei meinem ersten Gespann trat das Problem erst beim 3. Abladen auf, bei meinem 2. direkt schon beim ersten mal.
Es kann also eigentlich kein Problem von "ich kann den Weg nicht finden" sein, denn dann müsste das Problem ja jedes mal auftauchen, oder?

**Comment by Woife1** [comment]
kann es sein das der "Error" kommt sobald 2 Berechnungen fehlgeschlagen sind und er trotzdem bei der 3. oder 4. den Weg findet?

**Comment by Axel32019** [comment]
@Woife1 Es gibt keinen Zusammenhang zwischen einzelnen Berechnungen, jede wird komplett und ohne jeglichen Bezug auf andere / vorherige Daten / Ergebnisse durchgeführt.
