### ISSUE TITLE
Error: Running LUA method 'update'

### ISSUE THREAD

**Issue by Iwan1803** [Axel32019/FS19_AutoDriveLive#5]
Ich habe heute die AD-Version 1.0.7.0-10 geladen und die aktuelle Live-Datei und nun geht gar nichts mehr. Im Log taucht folgende Fehlermeldung wiederholt auf:

> 2019-11-27 20:00 Error: Running LUA method 'update'.
2019-11-27 20:00 D:/Dokumente/My Games/FarmingSimulator2019/mods/FS19_AutoDrive/scripts/AutoDriveDijkstraLive.lua:49: bad argument #1 to 'abs' (number expected, got nil)

Dabei war es egal, welches Fahrzeug ich genommen habe und welche AD-Option und welche/s Ziel/e ich eingestellt habe.
Ich habe es dann mal mit der AD-Version von Montag probiert und dort passiert das gleiche.

**Comment by Axel32019** [comment]
Hallo @Iwan1803,
Das kann m.E. nur auftreten wenn Du den neuen Schritt der Anleitung "übersehen" hast:
NEU: In Funktion AutoDrive:getDriveTimeBetweenNodes am Ende

return driveTime

ersetzen durch:

return driveTime, angle
Bitte überprüfe das mal...

**Comment by Iwan1803** [comment]
Oh man, hast recht... ich hab die Datei bisher einfach runtergeladen und fertig.
Ich hoffe mal, das Stephan das bald integrieren wird und das Chaos dann ein Ende hat 😉

**Comment by Axel32019** [comment]
@Iwan1803 Funktioniert es jetzt wieder?

**Comment by Iwan1803** [comment]
Ja, sieht gut aus, aber ich habe gestern nur einen kurzen Test gemacht.

**Comment by Iwan1803** [comment]
Scheint alles zu funktionieren.
