### ISSUE TITLE
Kürzeste / schnellste Strecke?

### ISSUE THREAD

**Issue by Iwan1803** [Axel32019/FS19_AutoDriveLive#6]
Ich weiß nicht, ob es ein Bug/Problem von AD Live ist, aber kann es sein, das Optionen von AD nicht berücksichtigt werden?
"Zielpunkte vermeiden" habe ich aktiviert und somit wurden gewisse Strecken vermieden. Mittlerweile ignorieren die Fahrzeuge das aber und stehen dann plötzlich hinter geparkten Fahrzeugen, wo sie eigentlich gar nicht lang fahren dürften. An meinem Werkstattpunkt sind die Abfahrer über die Ausweichstrecke vorbei gefahren und nun stehen sie hinter Fahrzeugen, die ich zur Reparatur dahin geschickt habe.

**Comment by Axel32019** [comment]
Hallo @Iwan1803,
Würdest Du mir bitte Dein Streckennetz zur Verfügung stellen und einen Screeshot von dem Szenario "Werkstattpunkt" mit eingeschaltetem Streckennetzt. Dann schaue ich es mir mal an.
https://github.com/Axel32019/FS19_AutoDriveLive/issues/new

**Comment by Iwan1803** [comment]
Die Abfahrer sollten den Wegpunkt der Werkstatt eigentlich vermeiden (gelbe Linie) und über die andere Strecke fahren (rote Linie), wie sie es bisher getan haben. Neuerdings machen sie das aber nicht mehr.
Ich habe es auch an meinem Sägewerk gehabt: https://www.youtube.com/watch?v=yKPgRhONnNo&t=2430s (ab 40:30 Minuten). Direkt neben dem Anhänger ist eine Strecke ohne Zielpunkt und bisher wurde am Abladepunkt auch immer vorbeigefahren, aber hier nicht. Er "kürzt" hier am Sägewerk auch am Entnahmepunkt für Hackschnitzel die Abkürzung.
[AutoDrive.zip](https://github.com/Axel32019/FS19_AutoDriveLive/files/3907464/AutoDrive.zip)

![fsScreen_2019_11_30_20_10_01](https://user-images.githubusercontent.com/47528836/69904975-1b364480-13ae-11ea-8852-62957eda568c.jpg)
![fsScreen_2019_11_30_20_10_14](https://user-images.githubusercontent.com/47528836/69904976-1bcedb00-13ae-11ea-83a7-a7ea9b02aae5.jpg)

**Comment by Axel32019** [comment]
Eines mal vorweg: AD Live verwendet die Entfernungs- / Zeitberechnungs-routinen von AD (getDistanceBetweenNodes, getDriveTimeBetweenNodes), daher ja die Änderungen zur Verwendung in der Anleitung.
Deine Einstellung "Maximaler Umweg" steht, wenn ich es richtig sehe, auf 500m. Das ist relativ viel, habe ich in anderen AD...xml noch nicht gesehen, max. 10 oder 50m.
Die 2 Bilder verdeutlichen prinzipiell das Problem, aber das Video bringt mir wahrscheinlich mehr Erkenntnisse - Danke dafür!
Gehe jetzt mal in die Analyse...

**Comment by Iwan1803** [comment]
> Ich weiß nicht, ob es ein Bug/Problem von AD Live ist...

Ich dachte, ich poste es erstmal hier, bevor ich Stephan drauf ansetze 😉

"maximaler Umweg" steht bei mir sogar auf 1.000m, da es mir eigentlich egal ist, wieviel Umweg er fährt, aber wenn er trotz der Einstellung dennoch Zielpunkt-Strecken nutzt anstatt sie zu umfahren, sollte die Einstellung ja egal sein.
An der Werkstatt könnte ich den Weg anders aufzeichnen, um das "Problem" zu umgehen, aber am Sägewerk geht es halt nicht.
Falls du noch was brauchst, dann sag einfach Bescheid. Ich kann dir das ganze auch gerne mal live im Stream zeigen.

**Comment by Axel32019** [comment]
Frage: Wenn Du einen neuen Issue anlegst siehst Du dann das hinterlegte Template?

Zum Sägewerk:
Deine xml enthält neben dem Holzanhänger nur 2 Strecken, das Video zeigt jedoch 3.
Wahrscheinlich hast Du nach dem Anlegen der 3. Strecke nicht gespeichert.
Rein optisch würde ich sagen die Strecke mit dem Anhänger ist kürzer als die links vorbei führende.
Auch befindet sich auf der Strecke mit dem Anhänger keine Markierung, die Einstellung "Zielpunkte vermeiden" kann somit nicht greifen.
Würdest Du bitte die xml mit den 3 Strecken anhängen, dann kann ich das mal nachrechnen.
Ich schaue mir dann auch mal den Bereich der Werkstatt an.

**Comment by Iwan1803** [comment]
Ja, ich sehe das Template.

Beim Sägewerk musste ich die Strecke von 3 auf 2 reduzieren, da FED Action es verändert hat und nun dort, wo die 3. Strecke lang ging (am Zaun), eine Abladestelle für Paletten ist. Das Video zeigt noch die alte Version und wo der Anhänger steht bzw. vor dem Anhänger und seinem Dolly ist ein Zielpunkt für das Abladen der Holzstämme.
[AD-NFM-v1.1.zip](https://github.com/Axel32019/FS19_AutoDriveLive/files/3908053/AD-NFM-v1.1.zip)
Ich werde heute ab ca. 20 Uhr in meinem Stream die verschiedenen "Probleme" noch mal nachstellen.

**Comment by Iwan1803** [comment]
@Axel32019 
Ich hoffe das du trotz der Stream-Probleme verstanden hast, was ich meine. 
https://youtu.be/bPDyfqrNYTg
Es sieht halt so aus, als ob er die Einstellung bzgl. Zielpunkte umfahren völlig ignoriert. Ob dies an AD selber oder an AD Live liegt, kann ich nicht beurteilen. Ich könnte höchstens morgen noch mal einen Test ohne AD Live machen, falls das hilft.

**Comment by Axel32019** [comment]
Danke für die Demonstration der "Probleme" im Video!
Leider habe ich gerade keinen LS-Rechner zum Testen zur Verfügung und benötige Eure Rückmeldung.
Anbei eine Version die mir mehr Informationen liefern sollte.
Ich habe die Einstellungen kürzeste Route, 100m Umweg und Zielpunkte vermeiden fest codiert.
Die ersten 10 Routen werden einige Informationen in die log-Datei schreiben, es kann währenddessen zu leichten Rucklern kommen.
Bitte aus dem log die Zeilen mit "axel:" hier posten.
[AutoDriveDijkstraLive.zip](https://github.com/Axel32019/FS19_AutoDriveLive/files/3910434/AutoDriveDijkstraLive.zip)

**Comment by Iwan1803** [comment]
An meinem Werkstattpunkt fährt er nun vorbei, was schon mal sehr gut ist.
Allerdings habe ich nun Error von deinem Logging im Log:
> 2019-12-02 19:13 Error: Running LUA method 'update'.
2019-12-02 19:13 D:/Dokumente/My Games/FarmingSimulator2019/mods/FS19_AutoDrive/scripts/AutoDriveDijkstraLive.lua:238: bad argument #1 to 'tostring' (value expected)

**Comment by Axel32019** [comment]
Verdammt, bitte mal folgendes probieren:
[AutoDriveDijkstraLive.zip](https://github.com/Axel32019/FS19_AutoDriveLive/files/3912772/AutoDriveDijkstraLive.zip)

**Comment by Iwan1803** [comment]
Hier mal die Log-Einträge:
> 2019-12-02 22:05 axel: AutoDrive:dijkstraLive useFastestRoute nil
2019-12-02 22:05 axel: AutoDrive:getDriveTimeBetweenNodesLive mapMarker table: 0x022c0bcc43d8
2019-12-02 22:05 axel: AutoDrive:getDriveTimeBetweenNodesLive avoidMarkers nil
2019-12-02 22:05 axel: AutoDrive:getDriveTimeBetweenNodesLive mapMarkerDetour nil
2019-12-02 22:05 axel: AutoDrive:dijkstraLive useFastestRoute nil
2019-12-02 22:05 axel: AutoDrive:getDriveTimeBetweenNodesLive mapMarker table: 0x022c0bcc43d8
2019-12-02 22:05 axel: AutoDrive:getDriveTimeBetweenNodesLive avoidMarkers nil
2019-12-02 22:05 axel: AutoDrive:getDriveTimeBetweenNodesLive mapMarkerDetour nil
2019-12-02 22:08 axel: AutoDrive:dijkstraLive useFastestRoute nil
2019-12-02 22:08 axel: AutoDrive:getDriveTimeBetweenNodesLive mapMarker table: 0x022c0bcc43d8
2019-12-02 22:08 axel: AutoDrive:getDriveTimeBetweenNodesLive avoidMarkers nil
2019-12-02 22:08 axel: AutoDrive:getDriveTimeBetweenNodesLive mapMarkerDetour nil
2019-12-02 22:09 axel: AutoDrive:dijkstraLive useFastestRoute nil
2019-12-02 22:09 axel: AutoDrive:getDriveTimeBetweenNodesLive mapMarker table: 0x022c0bcc43d8
2019-12-02 22:09 axel: AutoDrive:getDriveTimeBetweenNodesLive avoidMarkers nil
2019-12-02 22:09 axel: AutoDrive:getDriveTimeBetweenNodesLive mapMarkerDetour nil
2019-12-02 22:09 axel: AutoDrive:dijkstraLive useFastestRoute nil
2019-12-02 22:09 axel: AutoDrive:getDriveTimeBetweenNodesLive mapMarker table: 0x022c0bcc43d8
2019-12-02 22:09 axel: AutoDrive:getDriveTimeBetweenNodesLive avoidMarkers nil
2019-12-02 22:09 axel: AutoDrive:getDriveTimeBetweenNodesLive mapMarkerDetour nil

![fsScreen_2019_12_02_22_19_29](https://user-images.githubusercontent.com/47528836/69996272-fda1e000-1551-11ea-8a79-d947b0002be7.jpg)

**Comment by Axel32019** [comment]
Vielen Dank! 
Leider sieht das aus wie ich es befürchtet habe: Die Einstellungen "kommen nicht an". Da muss ich mal weiter schauen woran das liegt.

**Comment by Iwan1803** [comment]
> Leider habe ich gerade keinen LS-Rechner zum Testen zur Verfügung

Was hast du denn angestellt? 😲
Falls ich helfen kann, dann einfach Bescheid geben. Ich hab dir auf Discord mal eine FA geschickt.

**Comment by Axel32019** [comment]
Musste meinen Kurzurlaub wegen Krankheitsfall in der Familie verlängern...
Auf meinem jetzigen Alt-Lappi hab ich halt nicht alle Möglichkeiten, aber LUA programmieren geht noch.
Daher ist jede Hilfe beim Testen willkommen, kann nur in meiner PC-Testumgebung versuchen was ich kann, leider nicht in LS.
Wenn nötig pack ich hier, wie oben, ein zip zum Testen rein. 
Vielen Dank für die Unterstützung!

**Comment by Axel32019** [comment]
Brauche nochmals eine Rückmeldung. Funktion wie vorher, nur einige zusäztliche Ausgaben im log.
[AutoDriveDijkstraLive.zip](https://github.com/Axel32019/FS19_AutoDriveLive/files/3917994/AutoDriveDijkstraLive.zip)

**Comment by Iwan1803** [comment]
Uh, kurz vor dem Stream, aber kein Problem, muss ja nur die Datei austauschen 😎
Gibt es eigentlich einen Konsolenbefehl, um einen Mod im laufenden Spiel neu zu laden? 🤔

**Comment by Axel32019** [comment]
Genau.
Mod laden im Spiel hab ich mal bei CP gesehen, ist aber nicht so einfach, läuft über eine generierte xml-Datei :-(

**Comment by Iwan1803** [comment]
> 2019-12-03 19:43 Error: Running LUA method 'update'.
2019-12-03 19:43 D:/Dokumente/My Games/FarmingSimulator2019/mods/FS19_AutoDrive/scripts/AutoDriveUtilFuncs.lua:99: bad argument #1 to 'atan2' (number expected, got nil)

![image](https://user-images.githubusercontent.com/47528836/70080009-179cfa80-1606-11ea-9b0e-b833c567a8d8.png)

**Comment by Axel32019** [comment]
Kommt da noch ein Callstack?

**Comment by Iwan1803** [comment]
Nein, nur die o.g. Meldung in der Log.txt. Die Passage aus der entsprechenden Datei habe ich mal angehangen. Ich weiß ja nicht, ob da was geändert worden ist.

**Comment by Axel32019** [comment]
Nimm erstmal die Version von gestern.

**Comment by Iwan1803** [comment]
Alles klar. Meld dich einfach, wenn es was neues zum Testen gibt 😉

**Comment by Axel32019** [comment]
@Iwan1803 Hier eine neue Version zum Testen und Bitte um Rückmeldung der log-Einträge
[AutoDriveDijkstraLive.zip](https://github.com/Axel32019/FS19_AutoDriveLive/files/3928264/AutoDriveDijkstraLive.zip)

**Comment by Iwan1803** [comment]
> 2019-12-05 19:52 Error: Running LUA method 'update'.
2019-12-05 19:52 D:/Dokumente/My Games/FarmingSimulator2019/mods/FS19_AutoDrive/scripts/AutoDriveUtilFuncs.lua:99: bad argument #1 to 'atan2' (number expected, got nil)

**Comment by Axel32019** [comment]
Die Jungs haben die Notation einiger Funktionen "aufgeräumt" (: <=>.). Darauf muss man erstmal kommen.. Daher neuer Versuch:
[AutoDriveDijkstraLive.zip](https://github.com/Axel32019/FS19_AutoDriveLive/files/3929202/AutoDriveDijkstraLive.zip)

**Comment by Iwan1803** [comment]
Ich werde das nachher testen.
Im übrigen bin ich mehrfach gefragt worden, wie man an AD Live rankommt. Da nicht jeder fähig ist, die notwendigen Anpassungen zu machen, würde ich gerne (regelmäßig) die aktuelle AD-Version mit Live ergänzen und dann hier hochladen. Was hälst du davon?

**Comment by Iwan1803** [comment]
So, bitte schön:
> 2019-12-06 18:04 axel: AutoDrive:dijkstraLive AutoDrive not nil OK
2019-12-06 18:04 axel: AutoDrive:dijkstraLive getSetting not nil OK
2019-12-06 18:04 axel: AutoDrive:dijkstraLive useFastestRoute false
2019-12-06 18:04 axel: AutoDrive:dijkstraLive avoidMarkers true
2019-12-06 18:04 axel: AutoDrive:dijkstraLive mapMarkerDetour 50
2019-12-06 18:04 axel: AutoDrive:dijkstraLive mapMarker table: 0x02c809c76d00
2019-12-06 18:04 axel: AutoDrive:dijkstraLive drawHeight 0.3

Alle geloggten Ergebnisse sahen gleich aus.

**Comment by Axel32019** [comment]
Das sieht gut aus. Beim Testen ruhig auch mal mit den Einstellungen "Zielpunkte vermeiden" ein/aus, kürzeste/schnellste Route, max. Umweg "rumspielen"...
Vielen Dank wieder fürs Testen. Wenn's nach Plan läuft bin ich ab Montag wieder im LS dabei.

Zum Kommentar mit der kompletten AD-Version + Live:
Ich würde es bevorzugen die positiven Testergebnisse an Stephan zu berichten und somit eine zügige Integration in AD anzustreben, sonst hächeln wir hier noch ewig den Versionen hinterher. Zumal ja zunehmend auch an der Zusammenarbeit mit CP gearbeitet wird, die Darstellung des aktuellen WP auch mal vor- und zurückgeschoben wird und vieles mehr.
Was meinst Du / meint Ihr zu diesem Ansatz?

**Comment by Iwan1803** [comment]
Stephan hatte zwar gesagt, das er es gut findet, aber ob er AD Live wirklich integrieren wird, ist mir nicht bekannt. Hier sollte man vielleicht noch mal nachhaken...
Ich werde weitertesten, aber loggt er immer noch nur max. 10x oder permanent?

**Comment by Axel32019** [comment]
Ja, geloggt werden 10x, habe ich so eingestellt damit nicht ständig "Ruckler" auftreten (könnten). Die notwendigen Infos habe ich ja jetzt und kann ein neues Release einstellen.

**Comment by Iwan1803** [comment]
Ok, dann werde ich mal mit der aktuellen "Beta" weitermachen und mit den Einstellungen rumspielen. Brauchst du die Logs dann noch?

**Comment by Axel32019** [comment]
Momentan nicht - Danke fürs Testen und viel Spass & Erfolg :-)

**Comment by Iwan1803** [comment]
Alles klar, dann warten wir mal auf Stephan sein Feedback.
Wenn er es nicht integriert, dann wäre er schön blöd, weil es einfach einen enormen Vorteil bietet.
Vielen Dank auf jeden Fall für die Arbeit!

**Comment by Axel32019** [comment]
@Iwan1803 Wenn OK, schließt der Ersteller den Issue, richtig?

**Comment by Iwan1803** [comment]
@Axel32019 
ja, ich mache hier mal zu, da die Integration in AD erfolgreich war.
Nochmal vielen Dank für deine Arbeit!
